apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: latifyildirim/web_server:latest
        resources: 
        ports:
        - containerPort: 80
        env: 
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: servers-cm
              key: MYSQL_USER
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: servers-cm
              key: MYSQL_DATABASE
        - name: MYSQL_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: servers-cm
              key: MYSQL_DATABASE_HOST
