- name: configure postgre instance 
  hosts: _ansible_postgresql
  become: true
  vars_files:
    -  secret.yml
  tasks:
    # - name: update all packages
    #   ansible.builtin.yum:
    #     name: '*'
    #     state: latest
    # - name: remove old docker packages
    #   ansible.builtin.yum:
    #     name:
    #       - docker 
    #       - docker-client 
    #       - docker-client-latest 
    #       - docker-common 
    #       - docker-latest 
    #       - docker-latest-logrotate 
    #       - docker-logrotate 
    #       - docker-engine
    #     state: removed

    # - name: install yum utils
    #   ansible.builtin.yum:
    #     name: "yum-utils"
    #     state: latest
    
    # - name: add docker repo
    #   ansible.builtin.get_url:
    #     url: https://download.docker.com/linux/centos/docker-ce.repo
    #     dest: /etc/yum.repos.d/docker-ce.repo # /etc/yum.repos.d/docker-ce.repo
      
    # - name: install docker
    #   ansible.builtin.package:
    #     name:  docker-ce 
    #     state: latest

    # - name: add ec2-user to docker group
    #   ansible.builtin.user:
    #     name: ec2-user
    #     groups: docker  # sudo usermod -a -G docker ec2-user  "bunun ansible hali"
    #     append: yes

    # - name: start docker service
    #   ansible.builtin.service:
    #     name: docker
    #     state: started
    #     enabled: yes
        
    - name: Copy files to the postgresql node
      ansible.builtin.copy:
        src: /home/ec2-user/ansible-project/postgres/
        dest: /home/ec2-user/postgresql

    - name: remove latif_postgre
      community.docker.docker_container:
        name: latif_postgre
        state: absent
        force_kill: true
    
    - name: delete latif/postgre image
      community.docker.docker_image:
        name: latif/postgre
        state: absent
    
    - name: build docker image
      community.docker.docker_image:
        name: latif/postgre
        build:
          path: /home/ec2-user/postgresql
        source: build
        state: present
      register: image_info
    
    - name: print the image image_info
      ansible.builtin.debug:
        var: image_info

    - name: Launch postgresql docker_container 
      community.docker.docker_container:
        name: latif_postgre
        image: latif/postgre
        state: started
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: "{{ password }}" # "Pp123456789"
        volumes:
          - /db-data:/var/lib/postgresql/data
      register: container_info

    - name: print the container image_info
      ansible.builtin.debug:
        var: container_info