version: "3.7"

services:
  database:
    image: mysql:5.7
    # platform: linux/x86_64        Bu satiri Apple islemcili cihazlar icin yazioruz.
    restart: always                # Cunkü bu mysql:5.7 yi calistirmiyor
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: latif
      MYSQL_PASSWORD: Latif_123
    networks:
      - latifnet
  myapp:
    image: latifyildirim/bookstoreapi:latest
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - latifnet

networks:
  latifnet:
    driver: bridge
